name: Generate and check HTML

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the site with Jekyll
      run: |
        chmod o+rw ${{ github.workspace }}
        docker run -v ${{ github.workspace }}:/srv/jekyll jekyll/jekyll:3 jekyll build

    - name: Check the generated HTML
      uses: chabad360/htmlproofer@v1.1
      with:
        directory: _site
        arguments: --only-4xx --ignore-status-codes 403 --ignore-files "/docs/" --ignore-urls "#" --allow-missing-href=true --ignore-empty-alt=false
